# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PMTilesExporter
                                 A QGIS plugin
 Export selected layers as PMTiles with preserved rendering.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-19
        copyright            : (C) 2026 by TJL
        email                : sato@taguma.co.jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PMTilesExporter class from file PMTilesExporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pmtiles_exporter import PMTilesExporter
    return PMTilesExporter(iface)
